### ISSUE TITLE
Remove private Interlude.Assets submodule due to errors checking out

### ISSUE THREAD

**Issue by squeaktoy** [YAVSRG/YAVSRG#3]
The submodules cannot be cloned due to requiring authentication and 404 errors.

**Comment by percyqaz** [comment]
Please see the guide in README.md - You only need to clone two of the submodules to build, Interlude.Assets can be safely ignored but is there for my convenience (unless I think of a convenient way to have it for me but not cause errors for people without permission to see it)

```
# navigate to somewhere you like to store code
git clone https://github.com/YAVSRG/YAVSRG.git # don't use --recurse-submodules flag or Interlude.Assets will cause an error
git submodule update --init libraries/Percyqaz.Shell
git submodule update --init libraries/Percyqaz.Common
```

**Comment by percyqaz** [comment]
Update

I've removed Interlude.Assets as submodule (and for now, I will clone that repo inside this one for my use cases)
I've also updated the build scripts and README.md with updated instructions now that the process is slightly simpler

Both the process of building and the game itself are not tested on Linux very often, so if you encounter anything else while checking the game out do let me know
